import React from 'react'
import Head from "next/head";
import Image from "next/image";
import { Layout } from "../components/Layout";
import { Button, Col, Row, Stack } from "react-bootstrap";
import Link from "next/link";
import { Note, SimplifiedNote, Tag } from "./_types";
import dynamic from "next/dynamic";
import EditTagsModal from "../components/EditTagsModal";
const NoteList = dynamic(() => import("../components/NoteList"), {
  ssr: false,
});

type HomeProps = {
  availableTags: Tag[];
  notes: SimplifiedNote[];
  onAddTag:(tag:Tag) => void
};

export default function Home({ availableTags, notes, onAddTag }: HomeProps) {
  const [ShowEditModal, setShowEditModal] = React.useState(false)


  return (
    <>
      <Head>
        <title>Ag note</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen border">
        <Layout>
          <EditTagsModal
            ShowEditModal={ShowEditModal}
            setShowEditModal={setShowEditModal}
            onAddTag={onAddTag}
          />

          <Row className="align-items-center mb-4">
            <Col>
              <h1>Notes</h1>
            </Col>
            <Col xs="auto">
              <Stack gap={2} direction="horizontal">
                <Link href={"/new"}>
                  <Button variant="primary">Create</Button>
                </Link>
                <Button variant="outline-secondary" onClick={()=> setShowEditModal(true)}>Edit Tags</Button>
              </Stack>
            </Col>
          </Row>
          <NoteList availableTags={availableTags} notes={notes} />
        </Layout>
      </main>
    </>
  );
}
