import Head from "next/head";
import Image from "next/image";
import { Layout } from "../components/Layout";
import { Button, Col, Row, Stack } from "react-bootstrap";
import Link from "next/link";
import { Note, SimplifiedNote, Tag } from "./_types";
import dynamic from "next/dynamic";
const NoteList = dynamic(()=> import('../components/NoteList'), {ssr: false})


type HomeProps = {
  availableTags: Tag[];
  notes: SimplifiedNote[]
}

export default function Home({availableTags, notes}: HomeProps) {
  console.log('notes in home', notes)

  return (
    <>
      <Head>
        <title>Ag note</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Row className="align-items-center mb-4">
            <Col><h1>Notes</h1></Col>
            <Col xs="auto">
              <Stack gap={2} direction="horizontal">
                <Link href={'/new'}>
                  <Button variant="primary">Create</Button>
                </Link>
                <Button variant="outline-secondary">
                  Edit Tags
                </Button>
              </Stack>
            </Col>
          </Row>
          <NoteList availableTags={availableTags} notes={notes}/>
        </Layout>
      </main>
    </>
  );
}
