import Head from "next/head";
import Image from "next/image";
import { Layout } from "../components/Layout";
import NoteList from "../components/NoteList";

export default function Home() {
  

  return (
    <>
      <Head>
        <title>Ag note</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div>Notes</div>
          <NoteList />
        </Layout>
      </main>
    </>
  );
}
